name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Helloooo!!"
      - name: print goodbye
        run: echo "Byeeee !!!"
