name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: |
          echo "Helloooo!! First run"
          echo "Helloooo!! Second run"
      - name: print goodbye
        run: |
          echo "Byeeee !!! First run"
          echo "Byeeee !!! Second run"

